### ISSUE TITLE
Error message when activating non-existent project is unclean

### ISSUE THREAD

**Issue by harper25** [harper25/poetry-poems#4]
**Describe the bug**

Python exception with traceback appears when trying to activate non-exising project.

**To Reproduce**

1. Create a poetry project
2. Add it to poems
3. Delete the project
4. Try to activate the deleted project using poems:

```sh
~ $ poems deleted_project
Traceback (most recent call last):
  File "/usr/local/bin/poems", line 8, in <module>
    sys.exit(poems())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/poetry_poems/cli.py", line 133, in poems
    ensure_project_dir_has_env(environment.project_path)
  File "/usr/local/lib/python3.9/site-packages/poetry_poems/cli.py", line 214, in ensure_project_dir_has_env
    output, code = call_poetry_env(project_dir)
  File "/usr/local/lib/python3.9/site-packages/poetry_poems/poetry.py", line 49, in call_poetry_env
    output, code = PipedPopen(cmds=["poetry", "env", "list", "--full-path"], cwd=project_dir)
  File "/usr/local/lib/python3.9/site-packages/poetry_poems/poetry.py", line 10, in PipedPopen
    proc = Popen(cmds, stdout=PIPE, stderr=PIPE, env=env, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/olja9002/pylearn/deleted_project'
```

**Expected behavior**

Display a nice error message with suggestion to delete the project from poems project list. Also, make sure that proper error messages are displayed when using details view.

**Environment:**
 - OS: all
 - Poems Version [0.1.0]

**Comment by harper25** [comment]
Resolved in https://github.com/harper25/poetry-poems/pull/13
