### ISSUE TITLE
Poems failing to start on Windows

### ISSUE THREAD

**Issue by pjarnhus** [harper25/poetry-poems#8]
**Describe the bug**
When running poems on Windows, the program exists with a FileNotFoundError. When digging into this, it is because the POpen calls have been set with shell=False. On Windows this will make subprocess interpret the elements of the cmd list literally and it will therefore look for a file called poetry.

**To Reproduce**
1. Install poems on Windows
2. Run *poems*
3. See error
Traceback (most recent call last):
  File "c:\users\phrj\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\phrj\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\phrj\Miniconda3\Scripts\poems.exe\__main__.py", line 7, in <module>
  File "c:\users\phrj\miniconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\phrj\miniconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\phrj\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\phrj\miniconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\phrj\miniconda3\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\phrj\miniconda3\lib\site-packages\poetry_poems\cli.py", line 72, in poems
    poetry_config = PoetryConfig()
  File "c:\users\phrj\miniconda3\lib\site-packages\poetry_poems\poetry.py", line 58, in __init__
    self.call_poetry_virtualenvs_path()
  File "c:\users\phrj\miniconda3\lib\site-packages\poetry_poems\poetry.py", line 61, in call_poetry_virtualenvs_path
    output, code = PipedPopen(cmds=["poetry", "config", "virtualenvs.path"])
  File "c:\users\phrj\miniconda3\lib\site-packages\poetry_poems\poetry.py", line 10, in PipedPopen
    proc = Popen(cmds, stdout=PIPE, stderr=PIPE, env=env, **kwargs)
  File "c:\users\phrj\miniconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\phrj\miniconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Expected behavior**
The expected behaviour is that poems launches and presents a list of the added poetry projects

**Screenshots**

**Environment:**
 - OS: Win 10
 - Poems Version [e.g. 22] 0.2.0

**Additional context**

**Comment by pjarnhus** [comment]
I have opened a pull request with the changes that makes it run on Windows, if you are interested. The test suite fails on setup due to the same underlying issue, but I have not had the time to clean it up.

Let me know, if you are interested in collaborating on it. I think it is a really cool tool, that you have built.

**Comment by harper25** [comment]
Hi, @pjarnhus, great to hear from you, thanks for the issue, contribution and kind words. Of course I am interested in solving this issue and collaboration.

I tested the current version of the app on Win10 and also found some issues, but they are a bit different (I will post some screens). Several questions:
- which terminal app are you using?
- did you test your solution in the terminal of your choice? It can be done by:
  - deinstalling poetry-poems from your system
  - running 'poetry build' on your branch
  - installing generated wheel/tar on your system and testing
 
Screens from my testing, Windows 10 Home, 20H2.
1. Command Prompt - OK
![obraz](https://user-images.githubusercontent.com/37124475/110986328-d26d8980-836d-11eb-96dc-97d093d67f00.png)

2. Cmder - details not correct, also issues on left/right arrow on poems interactive screen
![obraz](https://user-images.githubusercontent.com/37124475/110986649-33955d00-836e-11eb-8703-cdfec94a2f73.png)

3. Mingw (Git Bash here) - not working, details not correct, also issues on left/right arrow on poems interactive screen
![obraz](https://user-images.githubusercontent.com/37124475/110986798-68091900-836e-11eb-9503-d7b95711a424.png)

**Comment by pjarnhus** [comment]
Hi,

Sorry for the long period of silence, there has been a lot on my plate recently. I did test it out and it is working on the rebuild version with  changes. I am using an Anaconda prompt, which as far as I know is simply a normal Windows command prompt with a few additions.

It is odd that I get the error, when your command prompt is working. My installation does not add python to the Windows path. I am not sure, if that is the reason behind the error though.

**Comment by harper25** [comment]
Resolved in: https://github.com/harper25/poetry-poems/pull/9
